
server:
  port: 8088
spring:
  application:
    name: StreamMessgaeHandle-1
  cloud:
    stream:
      bindings:
        example-topic-output:
          destination: test-topic
        example-topic-input:
          destination: test-topic
          consumer:
            max-attempts: 1
          group: stream-exception-handler
  rabbitmq:
    host: lcoalhost
    port: 5672
    username: guest
    password: guest
